### MACROS ###################################################################
macros:
  install:
    prefix: ["yay", "-S", "--noconfirm", "--needed"]

  install-pacman:
    prefix: ["sudo", "pacman", "-S", "--noconfirm", "--needed"]

  go-get:
    prefix: ["go", "get"]

  go-install:
    prefix: ["go", "install"]

  git-clone:
    deps: ["git"]
    prefix: ["git", "clone"]

  sudo-cp:
    prefix: ["sudo", "cp"]

  sudo-ln:
    prefix: ["sudo", "ln", "-s"]

### TASKS ####################################################################
tasks:
  ### Install yay
  yay:
    cmds:
      - ["@install-pacman", "yay"]

  git:
    cmds:
      - ["@install", "git"]

  scripts:
    cmds:
      - ["mkdir",  "-p", "$HOME/bin"]
    links:
      - ["bin/i3-goto-free-workspace.sh"]
      - ["bin/rofi-select-monitor-layout.sh"]

  ### Install common applications and configurations
  common:
    deps: ["yay", "scripts", "udiskie"]
    cmds:
      - ["@install", 
          "neovim", 
          "python-neovim",
          "rofi", 
          "ranger", 
          "zsh", 
          "termite", 
          "git",
          "vlc",
          "feh",
          "firefox",
          "python",
          "python-pip",
          "task",
          "manjaro-pulse",
          "pandoc",
          "pa-applet",
          "udiskie",
          "arandr"]

      # install zplugin
      - ["wget", "-O/tmp/install.sh", "https://raw.githubusercontent.com/zdharma/zplugin/master/doc/install.sh"]
      - ["sh", "/tmp/install.sh"]

    links:
      - [".config/nvim", "nvim"]
      - [".gitconfig", "git/gitconfig"]
      - [".zshrc", "zsh/zshrc"]
      - [".zshenv", "zsh/zshenv"]
      - [".aliases", "zsh/aliases"]
      - [".zspaceship", "zsh/zspaceship"] 
      - [".local/share/fonts", "fonts"]
      - [".local/share/backgrounds", "backgrounds"] 
      - [".config/ranger", "ranger"]
      - [".config/termite", "termite"]
      - [".config/rofi", "rofi"]
      - [".profile", "profile/profile"]
      - [".taskrc", "task/taskrc"]

  ### Unload speaker module
  unload-pc-speaker:
    accepts: [["bash", "-c", "'kmod list | grep -c pcspkr'"]]
    cmds:
      - ["sudo", "rmmod", "pcspkr"]

  ### Disable pc speaker
  #disable-pc-speaker:
  #  deps: ["unload-pc-speaker"]
  #  cmds:
  #    - ["sudo", "touch", "/etc/modprobe.d/nobeep.conf"]
  #    - ["bash", "-c", "'echo \"blacklist pcspkr\" | sudo tee -a /etc/modprobe.d/nobeep.conf'"]

  change-shell:
    rejects: [["test", '"/bin/zsh" = $SHELL']]
    cmds:
      - ["chsh", "-s", "/bin/zsh"]

  blueman:
    cmds: 
      - ["mkdir", "-p", "$HOME/dln"]
      - ["gsettings", "set", "org.blueman.transfer", "shared-path", "$HOME/dln"]

  java:
    cmds:
      - ["@install", "jdk-openjdk"]

  intellij:
    deps: ["java"]
    links:
      - [".ideavimrc", "intellij/ideavimrc"]

  udiskie:
    cmds:
      - ["@sudo-cp", "$HM_SRC/etc/udev/rules.d/99-udisks2.rules", "/etc/udev/rules.d"]

  pulse:
    rejects: [["test", "-L", "/etc/pulse/default.pa"]]
    cmds:
      - ["@sudo-ln", ".config/pulse/default.pa", "/etc/pulse/default.pa"]

  ### Default
  default:
    deps: ["common", "change-shell"]

  ### Desktop
  desktop:
    deps: ["default", "pulse", "intellij"]
    links: 
      - [".config/i3/config", "i3/config_desktop"]
      - [".config/i3status/config", "i3status/config_desktop"]
      - ["bin/output-mapping.txt", "bin/output-mapping-desktop.txt"]
    templates:
      - [".config/nitrogen/bg-saved.cfg", "nitrogen/bg-saved_desktop.cfg"]
      - [".config/nitrogen/nitrogen.cfg", "nitrogen/nitrogen_desktop.cfg"]
        
  ### Laptop
  laptop:
    deps: ["default", "intellij", "blueman"]
    links: 
      - [".config/i3/config", "i3/config_laptop"]
      - [".config/i3status/config", "i3status/config_laptop"]
    templates:
      - [".config/nitrogen/bg-saved.cfg", "nitrogen/bg-saved_laptop.cfg"]
      - [".config/nitrogen/nitrogen.cfg", "nitrogen/nitrogen_laptop.cfg"]
    
