### MACROS ###################################################################
macros:
  install:
    prefix: ["sudo", "pacman", "-S", "--noconfirm", "--needed"]

  clone:
    deps: ["git"]
    prefix: ["git", "clone"]

### TASKS ####################################################################
tasks:
  ### Install common applications and configurations
  common:
    cmds:
      - ["@install", 
          "neovim", 
          "python-neovim",
          "rofi", 
          "ranger", 
          "zsh", 
          "termite", 
          "git",
          "vlc",
          "feh",
          "firefox",
          "python",
          "python-pip",
          "manjaro-pulse",
          "pa-applet",
          "yay",
          "arandr"]

      # change shell to zsh
      - ["chsh", "-s", "/bin/zsh"]

      # install zplugin
      - ["wget", "-O/tmp/install.sh", "https://raw.githubusercontent.com/zdharma/zplugin/master/doc/install.sh"]
      - ["sh", "/tmp/install.sh"]

    links:
      - [".config/nvim", "nvim"]
      - [".gitconfig", "git/gitconfig"]
      - [".zshrc", "zsh/zshrc"]
      - [".zshenv", "zsh/zshenv"]
      - [".aliases", "zsh/aliases"]
      - [".zspaceship", "zsh/zspaceship"] 
      - [".local/share/fonts", "fonts"]
      - [".local/share/backgrounds", "backgrounds"] 
      - [".config/ranger", "ranger"]
      - [".config/termite", "termite"]
      - [".config/rofi", "rofi"]

  ### Unload speaker module
  unload-pc-speaker:
    accepts: [["bash", "-c", "'kmod list | grep -c pcspkr'"]]
    cmds:
      - ["sudo", "rmmod", "pcspkr"]

  ### Disable pc speaker
  #disable-pc-speaker:
  #  deps: ["unload-pc-speaker"]
  #  cmds:
  #    - ["sudo", "touch", "/etc/modprobe.d/nobeep.conf"]
  #    - ["bash", "-c", "'echo \"blacklist pcspkr\" | sudo tee -a /etc/modprobe.d/nobeep.conf'"]

  ### Configure blueman
  blueman:
    cmds: 
      - ["mkdir", "-p", "$HOME/dln"]
      - ["gsettings", "set", "org.blueman.transfer", "shared-path", "$HOME/dln"]

  ### Default
  default:
    deps: ["common"]

  ### Desktop
  desktop:
    deps: ["common"]
    links: 
      - [".config/i3/config", "i3/config_desktop"]
      - [".config/i3status/config", "i3status/config_desktop"]
      - [".config/pulse/default.pa", "pulse/default.pa"]
    templates:
      - [".config/nitrogen/bg-saved.cfg", "nitrogen/bg-saved_desktop.cfg"]
      - [".config/nitrogen/nitrogen.cfg", "nitrogen/nitrogen_desktop.cfg"]
        
  ### Laptop
  laptop:
    deps: ["common", "blueman"]
    links: 
      - [".config/i3/config", "i3/config_laptop"]
      - [".config/i3status/config", "i3status/config_laptop"]
    templates:
      - [".config/nitrogen/bg-saved.cfg", "nitrogen/bg-saved_laptop.cfg"]
      - [".config/nitrogen/nitrogen.cfg", "nitrogen/nitrogen_laptop.cfg"]
    
