export EDITOR=/usr/bin/nvim
export VISUAL=/usr/bin/nvim

export GOPATH=~/.local/share/go
export GOBIN=$HOME/go/bin

export SWT_GTK3=0

typeset -U path
path=(
  ~/bin
  $GOBIN
  ~/.local/bin
  $path[@]
)
